    CREATE table table9(
       data1 text,
       data2 text,
       value1 int,
       received_time timestamp,

       primary key ((data1, data2), value1, received_time)
    );

    CREATE table table10(
       data1 text,
       data2 text,
       value1 int,
       received_time timestamp,

       primary key ((data1, data2), value1, received_time)
    );

    CREATE table table11(
       data1 text,
       data2 text,
       value1 int,
       received_time timestamp,

       primary key ((data1, data2), value1, received_time)
    );