name: Build on Commit

on:
  - push

jobs:
  mvn:
    uses: netcracker/qubership-workflow-hub/.github/workflows/maven-publish.yml@main
    with:
      maven-command: "--batch-mode install -Dgpg.skip=true org.sonarsource.scanner.maven:sonar-maven-plugin:5.0.0.4389:sonar -Dsonar.projectKey=Netcracker_qubership-dbaas-client -Dsonar.organization=vladislav-larkin-test-organization -Dsonar.host.url=https://sonarcloud.io"
      server-id: github
      java-version: 21
    secrets:
      maven-token: ${{ secrets.GITHUB_TOKEN }}
      sonar-token: ${{ secrets.SONAR_TOKEN }}
